#!/bin/sh
# Enhanced generator for Copilot custom agent profiles (agent-creation SKILL)
set -euo pipefail

usage() {
  cat <<EOF
Usage: $0 --name NAME --description DESC [--tools "read,edit"] [--target vscode|github-copilot] [--mcp]
Creates: .agent-alchemy/agents/NAME.agent.md
This generator is part of the agent-creation SKILL.
EOF
  exit 1
}

NAME=""
DESC=""
TOOLS=""
TARGET=""
MCP=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --name) NAME="$2"; shift 2;;
    --description) DESC="$2"; shift 2;;
    --tools) TOOLS="$2"; shift 2;;
    --target) TARGET="$2"; shift 2;;
    --mcp) MCP=1; shift;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

if [ -z "$NAME" ] || [ -z "$DESC" ]; then
  echo "--name and --description are required"
  usage
fi

# sanitize name: allowed characters are . - _ a-z A-Z 0-9
SAFE_NAME=$(echo "$NAME" | tr ' ' '-' | sed 's/[^A-Za-z0-9._-]/-/g')
OUT_DIR=".agent-alchemy/agents"
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/${SAFE_NAME}.agent.md"

# prepare tools list
if [ -z "$TOOLS" ]; then
  TOOLS_LIST="['read']"
else
  # convert comma-separated to quoted list: read,edit -> ['read','edit']
  TOOLS_LIST="$(printf "'%s'," $(echo "$TOOLS" | sed 's/,/ /g'))"
  TOOLS_LIST="[${TOOLS_LIST%,}]"
fi

VERSION="0.1"
LASTUPDATED=$(date -u +%F)
TITLE="$SAFE_NAME"

cat > "$OUT_FILE" <<EOF
---
name: ${SAFE_NAME}
title: "${TITLE}"
description: "${DESC}"
version: '${VERSION}'
lastUpdated: ${LASTUPDATED}
aiContext: true
tools: ${TOOLS_LIST}
target: ${TARGET}
intents: ['create-agent']
keywords: ['copilot','agent','create-agent']
topics: ['agent-creation']
---

## ${SAFE_NAME}

This custom agent was generated by the agent-creation SKILL.

Instructions and behavior:

- Describe the agent's role and any usage examples here.

EOF

echo "Created agent profile: $OUT_FILE"

if [ "$MCP" -eq 1 ]; then
  MCP_FILE="$OUT_DIR/mcp-${SAFE_NAME}.json"
  cat > "$MCP_FILE" <<MCP
{
  "name": "mcp-${SAFE_NAME}",
  "type": "local",
  "command": "echo mcp stub",
  "tools": ["*"]
}
MCP
  echo "Created MCP stub: $MCP_FILE"
fi

exit 0
