#!/usr/bin/env bash
set -euo pipefail

# Generate skills-registry.json and SKILLS/README.md from SKILL.md frontmatter
SKILLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OUT_JSON="$SKILLS_DIR/skills-registry.json"
OUT_README="$SKILLS_DIR/README.md"

python3 - "$SKILLS_DIR" "$OUT_JSON" "$OUT_README" <<'PY'
import os,sys,json,re,ast
from pathlib import Path

base=Path(sys.argv[1])
out_json=Path(sys.argv[2])
out_readme=Path(sys.argv[3])

skills=[]
for md in base.rglob('SKILL.md'):
    try:
        text=md.read_text(encoding='utf-8')
        m=re.match(r'^---\n(.*?)\n---\n', text, re.S)
        if not m:
            continue
        fm={}
        for line in m.group(1).splitlines():
            if ':' not in line:
                continue
            k,v=line.split(':',1)
            k=k.strip()
            v=v.strip()
            try:
                # attempt literal eval for lists/strings
                val=ast.literal_eval(v)
            except Exception:
                # strip quotes if present
                val=v.strip(' "\'')
            fm[k]=val
        fm['path']=str(md.relative_to(base))
        skills.append(fm)
    except Exception as e:
        print('error parsing', md, e, file=sys.stderr)

out={'generatedAt': __import__('datetime').datetime.utcnow().isoformat()+'Z', 'skills': skills}
out_json.write_text(json.dumps(out, indent=2), encoding='utf-8')

# write README listing
lines=["# SKILLS index","","This file is autogenerated by `generate-registry.sh`.","","## Discovered SKILLS",""]
for s in skills:
    title=s.get('title', s.get('path'))
    intents=s.get('intents', [])
    runner=s.get('runner','')
    lines.append(f"### {title}")
    lines.append("")
    lines.append(f"- path: `{s.get('path')}`")
    if runner:
        lines.append(f"- runner: `{runner}`")
    if intents:
        if isinstance(intents, list):
            lines.append(f"- intents: `{', '.join(intents)}`")
        else:
            lines.append(f"- intents: `{intents}`")
    if s.get('keywords'):
        kws=s.get('keywords')
        if isinstance(kws, list):
            lines.append(f"- keywords: `{', '.join(kws)}`")
        else:
            lines.append(f"- keywords: `{kws}`")
    lines.append("")

out_readme.write_text('\n'.join(lines), encoding='utf-8')
PY

echo "Generated $OUT_JSON and $OUT_README"

echo "Generated $OUT_JSON and $OUT_README"
